name: scalingo_test
description: Test scalingo with Dart buildpack

version: 1.0.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3

dev_dependencies:
  lints: ^5.0.0
